version: 1

trail:
  attestations:
    - name: pull-request
      type: pull_request
  artifacts:
    - name: languages-start-points
      attestations:
        - name: snyk-container-scan
          type: snyk
        - name: snyk-code-scan-wip
          type: snyk
